version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gatherapp-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "gatherapp-db"]
      interval: 30s
      timeout: 60s
      retries: 5
  gatherapp.api:
    image: gatherapp.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
        restart: false
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/GatherAppAPI/appsettings.Development.json
